version: '3.1'

services:
  analytics:
    image: analytics
    ports:
      - "5000:5000"
    environment:
      API_PORT: 5000
      DB_NAME: infin
      DB_USER: infin
      DB_PORT: 5432
      DB_PWD: kohpien0Lu5ceheiG6kohchie0eiteeL
      DB_HOST: db
      DB_ANALYTICS: 'mongodb://analytics_db:27017/'
      DB_ANALYTICS_HOST: analytics_db
      DB_ANAlYTICS_PORT: 27017
  
  analytics_db:
    image: mongo
    ports:
      - "27017:27017"
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infin
      POSTGRES_PASSWORD: kohpien0Lu5ceheiG6kohchie0eiteeL
      POSTGRES_USER: infin
    volumes:
      - pgdata:/var/lib/postgresql/data

  infin:
    image: repo.treescale.com/infinions/infin:v0.0.3
    ports:
      - "4000:4000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_URL: ecto://infin:kohpien0Lu5ceheiG6kohchie0eiteeL@db/infin
      SECRET_KEY_BASE: vk31KWVZn5Kusu/SLCn2fSRh90QehFGEMP3OE4oNDNPdaijn91Soic0X22jrZaS+ 
      PORT: 4000
      PT_SIBSAPIMARKET_HOST: https://site1.sibsapimarket.com:8445/sibs/apimarket-sb
      PT_SIBSAPIMARKET_APIKEY: 073286e4-055b-472b-96ad-7ddd484333ec

volumes:
  pgdata:
